# Generated by Django 4.0.2 on 2022-02-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoDocumento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
