# Generated by Django 4.0.2 on 2022-02-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoDocumento', '0002_alter_tipodocumento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
